### ISSUE TITLE
怎么做好性能测试？ | geosmart's note

### ISSUE THREAD

**Issue by geosmart** [geosmart/geosmart.github.io#6]
http://geosmart.github.io/post/benchmark/

**Comment by blackfish-wu** [comment]
刚哥，gridea已用，果然定期来视奸总能有收获

**Comment by geosmart** [comment]
> 刚哥，gridea已用，果然定期来视奸总能有收获

**Comment by geosmart** [comment]
> 刚哥，gridea已用，果然定期来视奸总能有收获

Gridea UI交互做的不错，但是新生的还有很多待完善的，我折腾不动改github issue了
